export const UPDATE_TITLE = 'UPDATE_TITLE';

export const REQUEST_PROGRAMS = 'REQUEST_PROGRAMS';
export const RECEIVE_PROGRAMS = 'RECEIVE_PROGRAMS';

export const REQUEST_GROUPS = 'REQUEST_GROUPS';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';

export const REQUEST_SCHEDULE = 'REQUEST_SCHEDULE';
export const RECEIVE_SCHEDULE = 'RECEIVE_SCHEDULE';