export const SET_TITLE = 'SET_TITLE';
export const RESET_TITLE = 'RESET_TITLE';

export const REQUEST_PROGRAMS = 'REQUEST_PROGRAMS';
export const RECEIVE_PROGRAMS = 'RECEIVE_PROGRAMS';

export const REQUEST_GROUPS = 'REQUEST_GROUPS';
export const RECEIVE_GROUPS = 'RECEIVE_GROUPS';

export const REQUEST_SCHEDULE = 'REQUEST_SCHEDULE';
export const RECEIVE_SCHEDULE = 'RECEIVE_SCHEDULE';

export const LOAD_PROGRAMS = 'LOAD_PROGRAMS';
export const LOAD_SCHEDULE = 'LOAD_SCHEDULE';

export const SET_YEAR = 'SET_YEAR';
export const SET_GROUP = 'SET_GROUP';
export const SET_PROGRAM = 'SET_PROGRAM';
export const SET_STUDENT = 'SET_STUDENT';